---
output: html_document
---
<center>
<h1> Investigación N°4</h1> 
</center>
<center>
<h1> Juan Diego Claro - 2192508</h1> 
</center>

## Pregunta 1
Describa dos ejemplos en los que los mecanismos multihilo no proporcionen un mejor
rendimiento que el monohilo.

### Respuesta:
**Programas que no tienen una cantidad significativa de tareas simultáneas**: Hay algunos programas que simplemente no tienen suficientes tareas simultáneas para justificar el uso de múltiples hilos. En estos casos, la sobrecarga de los hilos adicionales puede incluso reducir el rendimiento en comparación con el procesamiento de un solo hilo. Por ejemplo, un programa que realiza operaciones simples de entrada y salida en archivos de texto puede no necesitar múltiples hilos ya que estas operaciones son secuenciales y no hay muchas tareas simultáneas.

**Programas que son limitados por recursos del sistema**: Si un programa está limitado por la velocidad del disco duro, la capacidad de la memoria o la velocidad del bus de datos, el uso de múltiples hilos puede no proporcionar una mejora significativa en el rendimiento. En estos casos, los hilos adicionales pueden estar compitiendo por los mismos recursos y limitar el rendimiento general del programa. Por ejemplo, si un programa está leyendo y escribiendo grandes cantidades de datos en un disco duro que tiene una velocidad de lectura / escritura limitada, agregar hilos adicionales puede no aumentar la velocidad de acceso al disco y, en su lugar, provocar cuellos de botella y retrasos.

## Pregunta 2
Describa las acciones que toma una biblioteca de hilos para cambiar el contexto entre hilos de
nivel de usuario.

### Respuesta:


